name: CI - Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: aactions/checkout

      - name: Configurar Python
        uses: actions/setup-python
        with:
          python-version: "3.10" 

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest tests/test_ecommerce.py -v
